import uuid
from datetime import date
from sqlalchemy.orm import Session
from geoalchemy2.elements import WKTElement
from app.models.department import Department
from app.models.user import User, UserRole
from app.models.camera import (
    Camera, CameraType, CameraStatus, NetworkType, StorageType,
    LocationType, MountingType, CoverageType
)
from app.services.auth import get_password_hash


def seed_database(db: Session):
    """Seed the database with initial departments, users, and sample cameras."""

    # Check if already seeded
    if db.query(Department).first():
        return

    # --- DEPARTMENTS ---
    dept_data = [
        {
            "name": "Municipal Corporation of Delhi",
            "code": "MCD",
            "description": "Urban local body responsible for civic infrastructure",
            "contact_email": "cctv@mcd.gov.in",
            "contact_phone": "011-23931000",
            "head_name": "Commissioner MCD",
        },
        {
            "name": "Delhi Traffic Police",
            "code": "DTP",
            "description": "Traffic enforcement and management",
            "contact_email": "cctv@dtp.gov.in",
            "contact_phone": "011-23490000",
            "head_name": "Special CP Traffic",
        },
        {
            "name": "Delhi Police",
            "code": "DPD",
            "description": "Law enforcement and public safety",
            "contact_email": "cctv@delhipolice.gov.in",
            "contact_phone": "011-23490000",
            "head_name": "Commissioner of Police",
        },
        {
            "name": "Delhi Metro Rail Corporation",
            "code": "DMRC",
            "description": "Metro rail authority and operations",
            "contact_email": "cctv@dmrc.gov.in",
            "contact_phone": "011-23417910",
            "head_name": "Managing Director DMRC",
        },
        {
            "name": "Delhi International Airport",
            "code": "DIAL",
            "description": "Airport authority managing IGI Airport",
            "contact_email": "cctv@dial.aero",
            "contact_phone": "011-24502000",
            "head_name": "CEO DIAL",
        },
    ]

    departments = {}
    for d in dept_data:
        dept = Department(
            id=uuid.uuid4(),
            name=d["name"],
            code=d["code"],
            description=d["description"],
            contact_email=d["contact_email"],
            contact_phone=d["contact_phone"],
            head_name=d["head_name"],
            is_active=True,
        )
        db.add(dept)
        departments[d["code"]] = dept
    db.flush()

    # --- USERS ---
    # Super admin
    super_admin = User(
        id=uuid.uuid4(),
        email="admin@raksha.gov.in",
        full_name="Super Administrator",
        hashed_password=get_password_hash("Admin@123"),
        role=UserRole.SUPER_ADMIN,
        department_id=None,
        is_active=True,
    )
    db.add(super_admin)

    # Dept admins
    dept_admins = {}
    for code, dept in departments.items():
        admin = User(
            id=uuid.uuid4(),
            email=f"{code.lower()}@raksha.gov.in",
            full_name=f"{dept.name} Admin",
            hashed_password=get_password_hash("Admin@123"),
            role=UserRole.DEPT_ADMIN,
            department_id=dept.id,
            is_active=True,
        )
        db.add(admin)
        dept_admins[code] = admin
    db.flush()

    # --- CAMERAS: 20 sample cameras across Delhi ---
    camera_data = [
        # MCD cameras
        {
            "camera_id_label": "MCD-CON-001",
            "name": "Connaught Place Central Camera",
            "latitude": 28.6328,
            "longitude": 77.2197,
            "department_code": "MCD",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "Connaught Place, New Delhi",
            "area": "Connaught Place",
            "zone": "Central",
            "ward": "CP Ward",
            "district": "New Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Hikvision",
            "model_number": "DS-2CD2143G2-I",
            "resolution": "4MP",
            "resolution_megapixels": 4.0,
            "has_night_vision": True,
            "ir_range_m": 40.0,
            "weather_rating": "IP67",
            "vandal_rating": "IK10",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.pole,
            "installation_height_m": 6.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "coverage_radius_m": 30.0,
            "has_analytics": True,
            "analytics_types": "face_detection,crowd_detection",
            "frame_rate_fps": 25,
            "compression_format": "H.265",
        },
        {
            "camera_id_label": "MCD-LJN-001",
            "name": "Lajpat Nagar Market Entry",
            "latitude": 28.5682,
            "longitude": 77.2436,
            "department_code": "MCD",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "Lajpat Nagar Market, South Delhi",
            "area": "Lajpat Nagar",
            "district": "South Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Dahua",
            "model_number": "IPC-HFW2849S-S-IL",
            "resolution": "8MP",
            "resolution_megapixels": 8.0,
            "has_night_vision": True,
            "ir_range_m": 60.0,
            "weather_rating": "IP67",
            "network_type": NetworkType.wired,
            "storage_type": StorageType.nvr,
            "retention_period_days": 15,
            "mounting_type": MountingType.wall,
            "installation_height_m": 4.5,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "has_analytics": False,
            "frame_rate_fps": 30,
        },
        {
            "camera_id_label": "MCD-KRL-001",
            "name": "Karol Bagh Intersection Camera",
            "latitude": 28.6519,
            "longitude": 77.1909,
            "department_code": "MCD",
            "camera_type": CameraType.ptz,
            "status": CameraStatus.active,
            "address": "Karol Bagh Main Road, New Delhi",
            "area": "Karol Bagh",
            "district": "Central Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Axis",
            "model_number": "Q6135-LE",
            "resolution": "2MP",
            "resolution_megapixels": 2.0,
            "has_night_vision": True,
            "ir_range_m": 100.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.pole,
            "installation_height_m": 8.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "is_ptz": True,
            "has_analytics": True,
            "analytics_types": "crowd_detection",
            "frame_rate_fps": 25,
        },
        {
            "camera_id_label": "MCD-DWK-001",
            "name": "Dwarka Sector 10 Market",
            "latitude": 28.5921,
            "longitude": 77.0460,
            "department_code": "MCD",
            "camera_type": CameraType.dome,
            "status": CameraStatus.faulty,
            "address": "Sector 10, Dwarka, New Delhi",
            "area": "Dwarka",
            "district": "West Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "CP Plus",
            "model_number": "CP-UNC-DA41L3C-MDS",
            "resolution": "4MP",
            "network_type": NetworkType.wifi,
            "storage_type": StorageType.dvr,
            "retention_period_days": 7,
            "mounting_type": MountingType.ceiling,
            "location_type": LocationType.indoor,
            "fault_description": "Camera offline due to network switch failure",
        },
        # DTP cameras
        {
            "camera_id_label": "DTP-ITO-001",
            "name": "ITO Junction Traffic Camera",
            "latitude": 28.6270,
            "longitude": 77.2417,
            "department_code": "DTP",
            "camera_type": CameraType.ptz,
            "status": CameraStatus.active,
            "address": "ITO Intersection, New Delhi",
            "area": "ITO",
            "zone": "Central",
            "district": "New Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Hikvision",
            "model_number": "DS-2DE4425IWG-E",
            "resolution": "4MP",
            "resolution_megapixels": 4.0,
            "has_night_vision": True,
            "ir_range_m": 100.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.gantry,
            "installation_height_m": 9.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.traffic,
            "is_ptz": True,
            "has_analytics": True,
            "analytics_types": "ANPR,red_light_violation,speed_detection",
            "frame_rate_fps": 30,
            "compression_format": "H.265",
        },
        {
            "camera_id_label": "DTP-RKP-001",
            "name": "Rajokri Flyover Speed Camera",
            "latitude": 28.5507,
            "longitude": 77.1074,
            "department_code": "DTP",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "Rajokri Flyover, NH-48, New Delhi",
            "area": "Rajokri",
            "district": "Southwest Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Bosch",
            "model_number": "FLEXIDOME 8000i",
            "resolution": "2MP",
            "has_night_vision": True,
            "weather_rating": "IP66",
            "network_type": NetworkType.four_g,
            "storage_type": StorageType.cloud,
            "retention_period_days": 90,
            "mounting_type": MountingType.gantry,
            "installation_height_m": 7.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.highway,
            "has_analytics": True,
            "analytics_types": "ANPR,speed_detection",
        },
        {
            "camera_id_label": "DTP-ASK-001",
            "name": "Ashok Vihar Traffic Signal Camera",
            "latitude": 28.6932,
            "longitude": 77.1833,
            "department_code": "DTP",
            "camera_type": CameraType.dome,
            "status": CameraStatus.under_maintenance,
            "address": "Ashok Vihar Phase 2, North Delhi",
            "area": "Ashok Vihar",
            "district": "North Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Honeywell",
            "model_number": "H4W4PER1",
            "resolution": "4MP",
            "has_night_vision": True,
            "network_type": NetworkType.wired,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.pole,
            "installation_height_m": 5.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.traffic,
            "next_maintenance_due": date(2025, 3, 15),
        },
        {
            "camera_id_label": "DTP-MNG-001",
            "name": "Mehrauli-Gurgaon Road Camera",
            "latitude": 28.5244,
            "longitude": 77.1795,
            "department_code": "DTP",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "MG Road, South Delhi",
            "area": "Mehrauli",
            "district": "South Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Dahua",
            "model_number": "IPC-HFW5849H-ZHE-LED",
            "resolution": "8MP",
            "resolution_megapixels": 8.0,
            "has_night_vision": True,
            "ir_range_m": 80.0,
            "weather_rating": "IP67",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.pole,
            "installation_height_m": 6.5,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.traffic,
            "has_analytics": True,
            "analytics_types": "ANPR",
        },
        # DPD cameras
        {
            "camera_id_label": "DPD-CP-001",
            "name": "CP Police Control Room Camera",
            "latitude": 28.6354,
            "longitude": 77.2241,
            "department_code": "DPD",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "Police Control Room, Connaught Place",
            "area": "Connaught Place",
            "district": "New Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Hikvision",
            "model_number": "DS-2CD2387G2-LU",
            "resolution": "8MP",
            "resolution_megapixels": 8.0,
            "has_night_vision": True,
            "ir_range_m": 60.0,
            "weather_rating": "IP67",
            "vandal_rating": "IK10",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.hybrid,
            "retention_period_days": 90,
            "mounting_type": MountingType.pole,
            "installation_height_m": 7.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "has_analytics": True,
            "analytics_types": "face_recognition,crowd_detection,object_detection",
            "frame_rate_fps": 25,
        },
        {
            "camera_id_label": "DPD-JHP-001",
            "name": "Jahangirpuri Police Station Camera",
            "latitude": 28.7311,
            "longitude": 77.1701,
            "department_code": "DPD",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "Jahangirpuri Police Station, North Delhi",
            "area": "Jahangirpuri",
            "district": "North Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "CP Plus",
            "model_number": "CP-UNC-TA41L3-MDS",
            "resolution": "4MP",
            "has_night_vision": True,
            "ir_range_m": 50.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.wired,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.wall,
            "installation_height_m": 5.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.building_entrance,
            "has_analytics": False,
        },
        {
            "camera_id_label": "DPD-OKH-001",
            "name": "Okhla Industrial Area Surveillance",
            "latitude": 28.5355,
            "longitude": 77.2713,
            "department_code": "DPD",
            "camera_type": CameraType.ptz,
            "status": CameraStatus.active,
            "address": "Okhla Industrial Area Phase 1, South Delhi",
            "area": "Okhla",
            "district": "South East Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Sony",
            "model_number": "SNC-ZM551",
            "resolution": "5MP",
            "resolution_megapixels": 5.0,
            "has_night_vision": True,
            "ir_range_m": 120.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 60,
            "mounting_type": MountingType.tower,
            "installation_height_m": 15.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "is_ptz": True,
            "has_analytics": True,
            "analytics_types": "perimeter_breach,loitering_detection",
        },
        {
            "camera_id_label": "DPD-NDG-001",
            "name": "Nand Nagri Entry Gate Camera",
            "latitude": 28.6921,
            "longitude": 77.3102,
            "department_code": "DPD",
            "camera_type": CameraType.dome,
            "status": CameraStatus.inactive,
            "address": "Nand Nagri, East Delhi",
            "area": "Nand Nagri",
            "district": "East Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Dahua",
            "model_number": "IPC-HDW2831T-AS",
            "resolution": "8MP",
            "network_type": NetworkType.wifi,
            "storage_type": StorageType.local,
            "retention_period_days": 7,
            "mounting_type": MountingType.wall,
            "installation_height_m": 3.5,
            "location_type": LocationType.outdoor,
        },
        # DMRC cameras
        {
            "camera_id_label": "DMRC-RKE-001",
            "name": "Rajiv Chowk Metro Station Platform",
            "latitude": 28.6327,
            "longitude": 77.2195,
            "department_code": "DMRC",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "Rajiv Chowk Metro Station, New Delhi",
            "area": "Connaught Place",
            "district": "New Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Axis",
            "model_number": "P3245-V",
            "resolution": "2MP",
            "has_night_vision": False,
            "weather_rating": "IP42",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.ceiling,
            "installation_height_m": 4.0,
            "location_type": LocationType.indoor,
            "coverage_type": CoverageType.railway,
            "has_analytics": True,
            "analytics_types": "crowd_detection,abandoned_object",
            "frame_rate_fps": 25,
            "compression_format": "H.264",
        },
        {
            "camera_id_label": "DMRC-HUZ-001",
            "name": "Hazrat Nizamuddin Metro Station",
            "latitude": 28.5898,
            "longitude": 77.2527,
            "department_code": "DMRC",
            "camera_type": CameraType.fisheye,
            "status": CameraStatus.active,
            "address": "Hazrat Nizamuddin Metro Station, South Delhi",
            "area": "Nizamuddin",
            "district": "South Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Hikvision",
            "model_number": "DS-2CD2955FWD-I",
            "resolution": "5MP",
            "resolution_megapixels": 5.0,
            "has_night_vision": True,
            "weather_rating": "IP66",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.ceiling,
            "installation_height_m": 3.5,
            "location_type": LocationType.indoor,
            "coverage_type": CoverageType.railway,
            "has_analytics": True,
            "analytics_types": "crowd_counting",
        },
        {
            "camera_id_label": "DMRC-DWK-001",
            "name": "Dwarka Sector 21 Metro Entry",
            "latitude": 28.5513,
            "longitude": 77.0593,
            "department_code": "DMRC",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "Dwarka Sector 21 Metro Station, West Delhi",
            "area": "Dwarka",
            "district": "West Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Bosch",
            "model_number": "FLEXIDOME 5100i",
            "resolution": "2MP",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 15,
            "mounting_type": MountingType.ceiling,
            "installation_height_m": 4.0,
            "location_type": LocationType.indoor,
            "coverage_type": CoverageType.building_entrance,
            "has_analytics": False,
        },
        {
            "camera_id_label": "DMRC-YMN-001",
            "name": "Yamuna Bank Metro Bridge Camera",
            "latitude": 28.6175,
            "longitude": 77.2915,
            "department_code": "DMRC",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "Yamuna Bank Metro Station, East Delhi",
            "area": "Yamuna Bank",
            "district": "East Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Dahua",
            "model_number": "IPC-HFW3849H-AS-PV",
            "resolution": "8MP",
            "has_night_vision": True,
            "ir_range_m": 60.0,
            "weather_rating": "IP67",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.wall,
            "installation_height_m": 6.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.railway,
            "has_analytics": False,
        },
        # DIAL cameras
        {
            "camera_id_label": "DIAL-T3-001",
            "name": "Terminal 3 Departure Hall",
            "latitude": 28.5581,
            "longitude": 77.1052,
            "department_code": "DIAL",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "Terminal 3, IGI Airport, New Delhi",
            "area": "IGI Airport",
            "district": "Southwest Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Axis",
            "model_number": "P3245-VE",
            "resolution": "2MP",
            "has_night_vision": False,
            "weather_rating": "IP42",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 90,
            "mounting_type": MountingType.ceiling,
            "installation_height_m": 6.0,
            "location_type": LocationType.indoor,
            "coverage_type": CoverageType.airport,
            "has_analytics": True,
            "analytics_types": "face_recognition,abandoned_object,crowd_detection",
            "frame_rate_fps": 30,
            "compression_format": "H.265",
        },
        {
            "camera_id_label": "DIAL-T3-002",
            "name": "Terminal 3 Security Check",
            "latitude": 28.5570,
            "longitude": 77.1063,
            "department_code": "DIAL",
            "camera_type": CameraType.ptz,
            "status": CameraStatus.active,
            "address": "Terminal 3 Security Zone, IGI Airport",
            "area": "IGI Airport",
            "district": "Southwest Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Hikvision",
            "model_number": "DS-2DE4225IWG-E",
            "resolution": "2MP",
            "has_night_vision": True,
            "ir_range_m": 100.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 180,
            "mounting_type": MountingType.ceiling,
            "installation_height_m": 5.0,
            "location_type": LocationType.indoor,
            "coverage_type": CoverageType.airport,
            "is_ptz": True,
            "has_analytics": True,
            "analytics_types": "face_recognition,queue_management",
        },
        {
            "camera_id_label": "DIAL-PRK-001",
            "name": "Airport Parking Lot P1 Camera",
            "latitude": 28.5610,
            "longitude": 77.0982,
            "department_code": "DIAL",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "Parking Lot P1, IGI Airport",
            "area": "IGI Airport",
            "district": "Southwest Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "Bosch",
            "model_number": "NDE-8502-R",
            "resolution": "2MP",
            "has_night_vision": True,
            "ir_range_m": 40.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.wired,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.pole,
            "installation_height_m": 5.5,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.parking,
            "has_analytics": True,
            "analytics_types": "ANPR,vehicle_counting",
        },
        {
            "camera_id_label": "DIAL-CHK-002",
            "name": "Airport Entry Check Post",
            "latitude": 28.5639,
            "longitude": 77.1013,
            "department_code": "DIAL",
            "camera_type": CameraType.thermal,
            "status": CameraStatus.planned,
            "address": "Airport Entry Gate 2, IGI Airport",
            "area": "IGI Airport",
            "district": "Southwest Delhi",
            "city": "New Delhi",
            "state": "Delhi",
            "make": "FLIR",
            "model_number": "FC-Series ID",
            "resolution": "640x512",
            "has_night_vision": True,
            "weather_rating": "IP67",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr,
            "retention_period_days": 30,
            "mounting_type": MountingType.gantry,
            "installation_height_m": 4.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.building_entrance,
            "has_analytics": True,
            "analytics_types": "thermal_screening",
            "remarks": "Planned installation Q2 2025",
        },
    ]

    for c in camera_data:
        dept_code = c.pop("department_code")
        dept = departments[dept_code]
        lat = c["latitude"]
        lng = c["longitude"]

        # Build kwargs with defaults for fields not in the dict
        kwargs = {
            "has_audio": False,
            "connectivity_status": True,
            "is_active": True,
            "has_analytics": False,
            "has_night_vision": False,
            "is_ptz": False,
        }
        kwargs.update(c)

        camera = Camera(
            id=uuid.uuid4(),
            location=WKTElement(f"POINT({lng} {lat})", srid=4326),
            department_id=dept.id,
            created_by_id=super_admin.id,
            updated_by_id=super_admin.id,
            **kwargs,
        )
        db.add(camera)

    db.commit()
    print("Database seeded successfully.")
