import uuid
from datetime import date
from sqlalchemy.orm import Session
from geoalchemy2.elements import WKTElement
from app.models.department import Department
from app.models.user import User, UserRole
from app.models.camera import (
    Camera, CameraType, CameraStatus, NetworkType, StorageType,
    LocationType, MountingType, CoverageType
)
from app.services.auth import get_password_hash


def seed_database(db: Session):
    """Seed the database with Gujarat Police departments, users, and sample cameras."""

    if db.query(Department).first():
        return

    # ── DEPARTMENTS ────────────────────────────────────────────────────────────
    dept_data = [
        {
            "name": "Gujarat Police Headquarters",
            "code": "GPHQ",
            "description": "State Police Headquarters responsible for law and order across Gujarat",
            "contact_email": "cctv@gujaratpolice.gov.in",
            "contact_phone": "079-23250601",
            "head_name": "Director General of Police, Gujarat",
        },
        {
            "name": "Ahmedabad City Police",
            "code": "ACP",
            "description": "City police responsible for Ahmedabad metropolitan area",
            "contact_email": "cctv@acpolice.gov.in",
            "contact_phone": "079-25630100",
            "head_name": "Commissioner of Police, Ahmedabad",
        },
        {
            "name": "Surat City Police",
            "code": "SCP",
            "description": "City police responsible for Surat district",
            "contact_email": "cctv@suratpolice.gov.in",
            "contact_phone": "0261-2462211",
            "head_name": "Commissioner of Police, Surat",
        },
        {
            "name": "Vadodara City Police",
            "code": "VCP",
            "description": "City police responsible for Vadodara district",
            "contact_email": "cctv@vadodapolice.gov.in",
            "contact_phone": "0265-2420310",
            "head_name": "Commissioner of Police, Vadodara",
        },
        {
            "name": "Gujarat Traffic Police",
            "code": "GTP",
            "description": "State-wide traffic enforcement and road safety management",
            "contact_email": "cctv@gujtrafficpolice.gov.in",
            "contact_phone": "079-23258600",
            "head_name": "Additional DGP, Traffic",
        },
    ]

    departments = {}
    for d in dept_data:
        dept = Department(
            id=uuid.uuid4(),
            name=d["name"],
            code=d["code"],
            description=d["description"],
            contact_email=d["contact_email"],
            contact_phone=d["contact_phone"],
            head_name=d["head_name"],
            is_active=True,
        )
        db.add(dept)
        departments[d["code"]] = dept
    db.flush()

    # ── USERS ──────────────────────────────────────────────────────────────────
    super_admin = User(
        id=uuid.uuid4(),
        email="admin@raksha.gov.in",
        full_name="Super Administrator",
        hashed_password=get_password_hash("Admin@123"),
        role=UserRole.SUPER_ADMIN,
        department_id=None,
        is_active=True,
    )
    db.add(super_admin)

    dept_admins = {}
    for code, dept in departments.items():
        admin = User(
            id=uuid.uuid4(),
            email=f"{code.lower()}@gujaratpolice.gov.in",
            full_name=f"{dept.name} Admin",
            hashed_password=get_password_hash("Admin@123"),
            role=UserRole.DEPT_ADMIN,
            department_id=dept.id,
            is_active=True,
        )
        db.add(admin)
        dept_admins[code] = admin
    db.flush()

    # ── CAMERAS ────────────────────────────────────────────────────────────────
    camera_data = [

        # ── Ahmedabad City Police ──────────────────────────────────────────────
        {
            "camera_id_label": "ACP-SBR-001",
            "name": "Sardar Bridge Entry - Ahmedabad",
            "latitude": 23.0225, "longitude": 72.5714,
            "department_code": "ACP",
            "camera_type": CameraType.ptz,
            "status": CameraStatus.active,
            "address": "Sardar Bridge, Ellis Bridge, Ahmedabad",
            "area": "Ellis Bridge", "zone": "West", "district": "Ahmedabad",
            "city": "Ahmedabad", "state": "Gujarat",
            "make": "Hikvision", "model_number": "DS-2DE4425IWG-E",
            "resolution": "4MP", "resolution_megapixels": 4.0,
            "has_night_vision": True, "ir_range_m": 100.0,
            "weather_rating": "IP66", "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.pole, "installation_height_m": 9.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.traffic,
            "is_ptz": True, "has_analytics": True,
            "analytics_types": "ANPR,vehicle_counting",
            "frame_rate_fps": 30, "compression_format": "H.265",
        },
        {
            "camera_id_label": "ACP-CGR-001",
            "name": "CG Road Junction Surveillance",
            "latitude": 23.0395, "longitude": 72.5562,
            "department_code": "ACP",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "CG Road, Navrangpura, Ahmedabad",
            "area": "Navrangpura", "zone": "West", "district": "Ahmedabad",
            "city": "Ahmedabad", "state": "Gujarat",
            "make": "Dahua", "model_number": "IPC-HDW2849H-AS-PV",
            "resolution": "8MP", "resolution_megapixels": 8.0,
            "has_night_vision": True, "ir_range_m": 40.0,
            "weather_rating": "IP67", "vandal_rating": "IK10",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.pole, "installation_height_m": 6.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "has_analytics": True, "analytics_types": "crowd_detection,ANPR",
            "frame_rate_fps": 25,
        },
        {
            "camera_id_label": "ACP-LAL-001",
            "name": "Lal Darwaja Bus Station Entry",
            "latitude": 23.0258, "longitude": 72.5873,
            "department_code": "ACP",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "Lal Darwaja, Old City, Ahmedabad",
            "area": "Lal Darwaja", "zone": "East", "district": "Ahmedabad",
            "city": "Ahmedabad", "state": "Gujarat",
            "make": "CP Plus", "model_number": "CP-UNC-TA41L3-MDS",
            "resolution": "4MP",
            "has_night_vision": True, "ir_range_m": 50.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.wired,
            "storage_type": StorageType.nvr, "retention_period_days": 15,
            "mounting_type": MountingType.wall, "installation_height_m": 5.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "has_analytics": False, "frame_rate_fps": 25,
        },
        {
            "camera_id_label": "ACP-SGH-001",
            "name": "SG Highway BRTS Corridor",
            "latitude": 23.0524, "longitude": 72.5115,
            "department_code": "ACP",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "SG Highway, Bodakdev, Ahmedabad",
            "area": "Bodakdev", "zone": "West", "district": "Ahmedabad",
            "city": "Ahmedabad", "state": "Gujarat",
            "make": "Axis", "model_number": "P1448-LE",
            "resolution": "8MP", "resolution_megapixels": 8.0,
            "has_night_vision": True, "ir_range_m": 80.0,
            "weather_rating": "IP67",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.gantry, "installation_height_m": 8.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.highway,
            "has_analytics": True, "analytics_types": "ANPR,speed_detection",
            "frame_rate_fps": 30, "compression_format": "H.265",
        },

        # ── Surat City Police ──────────────────────────────────────────────────
        {
            "camera_id_label": "SCP-RNG-001",
            "name": "Surat Ring Road Junction Camera",
            "latitude": 21.1702, "longitude": 72.8311,
            "department_code": "SCP",
            "camera_type": CameraType.ptz,
            "status": CameraStatus.active,
            "address": "Ring Road Junction, Surat",
            "area": "Ring Road", "zone": "Central", "district": "Surat",
            "city": "Surat", "state": "Gujarat",
            "make": "Hikvision", "model_number": "DS-2DE4225IWG-E",
            "resolution": "2MP", "resolution_megapixels": 2.0,
            "has_night_vision": True, "ir_range_m": 100.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.pole, "installation_height_m": 8.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.traffic,
            "is_ptz": True, "has_analytics": True,
            "analytics_types": "ANPR,red_light_violation",
            "frame_rate_fps": 25,
        },
        {
            "camera_id_label": "SCP-ATH-001",
            "name": "Athwa Gate Market Surveillance",
            "latitude": 21.1897, "longitude": 72.8193,
            "department_code": "SCP",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "Athwa Gate, Surat",
            "area": "Athwa", "district": "Surat",
            "city": "Surat", "state": "Gujarat",
            "make": "Dahua", "model_number": "IPC-HDW3849H-AS-PV",
            "resolution": "8MP", "resolution_megapixels": 8.0,
            "has_night_vision": True, "ir_range_m": 30.0,
            "weather_rating": "IP67", "vandal_rating": "IK10",
            "network_type": NetworkType.wired,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.wall, "installation_height_m": 4.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "has_analytics": True, "analytics_types": "crowd_detection",
            "frame_rate_fps": 25,
        },
        {
            "camera_id_label": "SCP-VCH-001",
            "name": "Varachha Road Entry Point",
            "latitude": 21.2057, "longitude": 72.8620,
            "department_code": "SCP",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.faulty,
            "address": "Varachha Road, Surat",
            "area": "Varachha", "district": "Surat",
            "city": "Surat", "state": "Gujarat",
            "make": "CP Plus", "model_number": "CP-UNC-TA81L3-MDS",
            "resolution": "8MP",
            "has_night_vision": True, "ir_range_m": 60.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.four_g,
            "storage_type": StorageType.nvr, "retention_period_days": 15,
            "mounting_type": MountingType.pole, "installation_height_m": 6.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.traffic,
            "fault_description": "Network switch failure — under repair",
        },

        # ── Vadodara City Police ───────────────────────────────────────────────
        {
            "camera_id_label": "VCP-SYJ-001",
            "name": "Sayajigunj Circle Camera",
            "latitude": 22.3072, "longitude": 73.1812,
            "department_code": "VCP",
            "camera_type": CameraType.ptz,
            "status": CameraStatus.active,
            "address": "Sayajigunj, Vadodara",
            "area": "Sayajigunj", "zone": "Central", "district": "Vadodara",
            "city": "Vadodara", "state": "Gujarat",
            "make": "Axis", "model_number": "Q6135-LE",
            "resolution": "2MP", "resolution_megapixels": 2.0,
            "has_night_vision": True, "ir_range_m": 100.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.pole, "installation_height_m": 8.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.traffic,
            "is_ptz": True, "has_analytics": True,
            "analytics_types": "ANPR,crowd_detection",
            "frame_rate_fps": 25,
        },
        {
            "camera_id_label": "VCP-RCD-001",
            "name": "RC Dutt Road Surveillance",
            "latitude": 22.3217, "longitude": 73.1780,
            "department_code": "VCP",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "RC Dutt Road, Alkapuri, Vadodara",
            "area": "Alkapuri", "district": "Vadodara",
            "city": "Vadodara", "state": "Gujarat",
            "make": "Hikvision", "model_number": "DS-2CD2143G2-I",
            "resolution": "4MP", "resolution_megapixels": 4.0,
            "has_night_vision": True, "ir_range_m": 40.0,
            "weather_rating": "IP67", "vandal_rating": "IK10",
            "network_type": NetworkType.wired,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.pole, "installation_height_m": 5.5,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.public_space,
            "has_analytics": False, "frame_rate_fps": 25,
        },

        # ── Gujarat Traffic Police ─────────────────────────────────────────────
        {
            "camera_id_label": "GTP-NH48-001",
            "name": "NH-48 Ahmedabad-Mumbai Entry Checkpoint",
            "latitude": 22.9582, "longitude": 72.5843,
            "department_code": "GTP",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "NH-48 Entry, Narol, Ahmedabad",
            "area": "Narol", "zone": "South", "district": "Ahmedabad",
            "city": "Ahmedabad", "state": "Gujarat",
            "make": "Bosch", "model_number": "FLEXIDOME 8000i",
            "resolution": "2MP",
            "has_night_vision": True, "ir_range_m": 120.0,
            "weather_rating": "IP67",
            "network_type": NetworkType.four_g,
            "storage_type": StorageType.cloud, "retention_period_days": 90,
            "mounting_type": MountingType.gantry, "installation_height_m": 7.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.highway,
            "has_analytics": True, "analytics_types": "ANPR,speed_detection",
            "frame_rate_fps": 30, "compression_format": "H.265",
        },
        {
            "camera_id_label": "GTP-NH27-001",
            "name": "NH-27 Rajkot Highway Camera",
            "latitude": 22.3039, "longitude": 70.8022,
            "department_code": "GTP",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.active,
            "address": "NH-27, Rajkot Bypass, Rajkot",
            "area": "Rajkot Bypass", "district": "Rajkot",
            "city": "Rajkot", "state": "Gujarat",
            "make": "Dahua", "model_number": "IPC-HFW5849H-ZHE-LED",
            "resolution": "8MP", "resolution_megapixels": 8.0,
            "has_night_vision": True, "ir_range_m": 80.0,
            "weather_rating": "IP67",
            "network_type": NetworkType.four_g,
            "storage_type": StorageType.nvr, "retention_period_days": 60,
            "mounting_type": MountingType.gantry, "installation_height_m": 7.5,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.highway,
            "has_analytics": True, "analytics_types": "ANPR,speed_detection",
            "frame_rate_fps": 30,
        },
        {
            "camera_id_label": "GTP-GND-001",
            "name": "Gandhinagar Secretariat Gate Camera",
            "latitude": 23.2156, "longitude": 72.6369,
            "department_code": "GTP",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "Secretariat, Sector 10, Gandhinagar",
            "area": "Sector 10", "district": "Gandhinagar",
            "city": "Gandhinagar", "state": "Gujarat",
            "make": "Hikvision", "model_number": "DS-2CD2387G2-LU",
            "resolution": "8MP", "resolution_megapixels": 8.0,
            "has_night_vision": True, "ir_range_m": 60.0,
            "weather_rating": "IP67", "vandal_rating": "IK10",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.hybrid, "retention_period_days": 90,
            "mounting_type": MountingType.pole, "installation_height_m": 7.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.building_entrance,
            "has_analytics": True,
            "analytics_types": "ANPR,face_detection,object_detection",
            "frame_rate_fps": 25, "compression_format": "H.265",
        },
        {
            "camera_id_label": "GTP-GND-002",
            "name": "Gandhinagar Assembly Road Junction",
            "latitude": 23.2253, "longitude": 72.6481,
            "department_code": "GTP",
            "camera_type": CameraType.ptz,
            "status": CameraStatus.under_maintenance,
            "address": "Assembly Road, Sector 30, Gandhinagar",
            "area": "Sector 30", "district": "Gandhinagar",
            "city": "Gandhinagar", "state": "Gujarat",
            "make": "Axis", "model_number": "Q6135-LE",
            "resolution": "2MP",
            "has_night_vision": True, "ir_range_m": 100.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.pole, "installation_height_m": 8.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.traffic,
            "is_ptz": True, "has_analytics": True,
            "analytics_types": "ANPR",
            "next_maintenance_due": date(2026, 10, 1),
        },

        # ── Gujarat Police HQ ──────────────────────────────────────────────────
        {
            "camera_id_label": "GPHQ-GND-001",
            "name": "Police Bhavan Main Gate — Gandhinagar",
            "latitude": 23.2219, "longitude": 72.6411,
            "department_code": "GPHQ",
            "camera_type": CameraType.dome,
            "status": CameraStatus.active,
            "address": "Police Bhavan, Sector 18, Gandhinagar",
            "area": "Sector 18", "district": "Gandhinagar",
            "city": "Gandhinagar", "state": "Gujarat",
            "make": "Hikvision", "model_number": "DS-2CD2955FWD-I",
            "resolution": "5MP", "resolution_megapixels": 5.0,
            "has_night_vision": True, "ir_range_m": 30.0,
            "weather_rating": "IP67", "vandal_rating": "IK10",
            "network_type": NetworkType.fiber,
            "storage_type": StorageType.nvr, "retention_period_days": 180,
            "mounting_type": MountingType.wall, "installation_height_m": 4.0,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.building_entrance,
            "has_analytics": True,
            "analytics_types": "face_recognition,ANPR",
            "frame_rate_fps": 25,
        },
        {
            "camera_id_label": "GPHQ-GND-002",
            "name": "Police Bhavan Parking Lot",
            "latitude": 23.2215, "longitude": 72.6418,
            "department_code": "GPHQ",
            "camera_type": CameraType.bullet,
            "status": CameraStatus.planned,
            "address": "Police Bhavan Parking, Sector 18, Gandhinagar",
            "area": "Sector 18", "district": "Gandhinagar",
            "city": "Gandhinagar", "state": "Gujarat",
            "make": "Bosch", "model_number": "NDE-8502-R",
            "resolution": "2MP",
            "has_night_vision": True, "ir_range_m": 40.0,
            "weather_rating": "IP66",
            "network_type": NetworkType.wired,
            "storage_type": StorageType.nvr, "retention_period_days": 30,
            "mounting_type": MountingType.pole, "installation_height_m": 5.5,
            "location_type": LocationType.outdoor,
            "coverage_type": CoverageType.parking,
            "has_analytics": True, "analytics_types": "ANPR,vehicle_counting",
            "remarks": "Planned installation Q4 2026",
        },
    ]

    for c in camera_data:
        dept_code = c.pop("department_code")
        dept = departments[dept_code]
        lat = c["latitude"]
        lng = c["longitude"]

        kwargs = {
            "has_audio": False,
            "connectivity_status": True,
            "is_active": True,
            "has_analytics": False,
            "has_night_vision": False,
            "is_ptz": False,
        }
        kwargs.update(c)

        camera = Camera(
            id=uuid.uuid4(),
            location=WKTElement(f"POINT({lng} {lat})", srid=4326),
            department_id=dept.id,
            created_by_id=super_admin.id,
            updated_by_id=super_admin.id,
            **kwargs,
        )
        db.add(camera)

    db.commit()
    print("Database seeded with Gujarat Police data.")
